import { AiFillStar } from "react-icons/ai";
import img1 from '../assets/menshoe3 Black.jpg'
import img2 from '../assets/flatshoe1.jpg'
import img3 from '../assets/flatshoe2.jpg'
import img4 from '../assets/Sneaker Mix Black.jpg'
import img5 from '../assets/sneaker3.jpg'
import img6 from '../assets/wshoe1.jpg'
import img7 from '../assets/wshoe3.jpg'

const data = [
  {
    img: img2,
    title: "Flat WalkerAbout Shoe",
    star: <AiFillStar className="ratings-start" />,
    reviews: "(123 reviews)",
    prevPrice: "₦5,000",
    newPrice: "10k",
    company: "Nike",
    color: "blue",
    category: "flats",
  },
  {
    img: img3,
    title: "Flat WalkerAbout Shoe",
    star: <AiFillStar className="ratings-start" />,
    reviews: "(123 reviews)",
    prevPrice: "₦5,000",
    newPrice: "10k",
    company: "Nike",
    color: "black",
    category: "flats",
  },
  {
    img: "https://m.media-amazon.com/images/I/6125yAfsJKL._AC_UX575_.jpg",
    title: "Nike Air Monarch IV",
    star: <AiFillStar className="ratings-start" />,
    reviews: "(123 reviews)",
    prevPrice: "₦5,000",
    newPrice: "10k",
    company: "Nike",
    color: "white",
    category: "sneakers",
  },
  {
    img: img4,
    title: "Nike Air Monarch IV",
    star: <AiFillStar className="ratings-start" />,
    reviews: "(123 reviews)",
    prevPrice: "₦5,000",
    newPrice: "10k",
    company: "Nike",
    color: "black-white",
    category: "sneakers",
  },
  {
    img: img5,
    title: "Nike Air Monarch IV",
    star: <AiFillStar className="ratings-start" />,
    reviews: "(123 reviews)",
    prevPrice: "₦5,000",
    newPrice: "10k",
    company: "Nike",
    color: "black",
    category: "sneakers",
  },
  {
    img: "https://m.media-amazon.com/images/I/519MRhRKGFL._AC_UX575_.jpg",
    title: "Nike Air Vapormax Plus",
    star: <AiFillStar className="ratings-start" />,
    reviews: "(123 reviews)",
    prevPrice: "₦5,000",
    newPrice: "10k",
    company: "Nike",
    color: "red",
    category: "sneakers",
  },

  {
    img: "https://m.media-amazon.com/images/I/51+P9uAvb1L._AC_UY695_.jpg",
    title: "Nike Waffle One Sneaker",
    star: <AiFillStar className="ratings-start" />,
    reviews: "(123 reviews)",
    prevPrice: "₦5,000",
    newPrice: "10k",
    company: "Nike",
    color: "green",
    category: "sneakers",
  },
  {
    img: "https://m.media-amazon.com/images/I/71oEKkghg-L._AC_UX575_.jpg",
    title: "Nike Running Shoe",
    star: <AiFillStar className="ratings-start" />,
    reviews: "(123 reviews)",
    prevPrice: "₦5,000",
    newPrice: "10k",
    company: "Adidas",
    color: "black",
    category: "sneakers",
  },
  {
    img: "https://m.media-amazon.com/images/I/41M54ztS6IL._AC_SY625._SX._UX._SY._UY_.jpg",
    title: "Flat Slip On Pumps",
    star: <AiFillStar className="ratings-start" />,
    reviews: "(123 reviews)",
    prevPrice: "₦5,000",
    newPrice: "10k",
    company: "Vans",
    color: "green",
    category: "flats",
  },
  {
    img: "https://m.media-amazon.com/images/I/71zKuNICJAL._AC_UX625_.jpg",
    title: "Knit Ballet Flat",
    star: <AiFillStar className="ratings-start" />,
    reviews: "(123 reviews)",
    prevPrice: "₦5,000",
    newPrice: "10k",
    company: "Adidas",
    color: "black",
    category: "flats",
  },

  {
    img: "https://m.media-amazon.com/images/I/61V9APfz97L._AC_UY695_.jpg",
    title: "Loafer Flats",
    star: <AiFillStar className="ratings-start" />,
    reviews: "(123 reviews)",
    prevPrice: "₦5,000",
    newPrice: "10k",
    company: "Vans",
    color: "white",
    category: "flats",
  },

  {
    img: "https://m.media-amazon.com/images/I/71VaQ+V6XnL._AC_UY695_.jpg",
    title: "Nike Zoom Freak",
    star: <AiFillStar className="ratings-start" />,
    reviews: "(123 reviews)",
    prevPrice: "₦5,000",
    newPrice: "10k",
    company: "Nike",
    color: "green",
    category: "sneakers",
  },

  {
    img: "https://m.media-amazon.com/images/I/61-cBsLhJHL._AC_UY695_.jpg",
    title: "Nike Men's Sneaker",
    star: <AiFillStar className="ratings-start" />,
    reviews: "(123 reviews)",
    prevPrice: "₦5,000",
    newPrice: "10k",
    company: "Adidas",
    color: "blue",
    category: "sneakers",
  },

  {
    img: "https://m.media-amazon.com/images/I/81xXDjojYKS._AC_UX575_.jpg",
    title: "PUMA BLACK-OCE",
    star: <AiFillStar className="ratings-start" />,
    reviews: "(123 reviews)",
    prevPrice: "₦5,000",
    newPrice: "30k",
    company: "Puma",
    color: "green",
    category: "sneakers",
  },
  {
    img: "https://m.media-amazon.com/images/I/71E75yRwCDL._AC_UY575_.jpg",
    title: "Pacer Future Sneaker",
    star: <AiFillStar className="ratings-start" />,
    reviews: "(123 reviews)",
    prevPrice: "₦5,000",
    newPrice: "30k",
    company: "Puma",
    color: "red",
    category: "sneakers",
  },
  {
    img: "https://m.media-amazon.com/images/I/71jeoX0rMBL._AC_UX575_.jpg",
    title: "Unisex-Adult Super",
    star: <AiFillStar className="ratings-start" />,
    reviews: "(123 reviews)",
    prevPrice: "₦5,000",
    newPrice: "30k",
    company: "Puma",
    color: "black",
    category: "sneakers",
  },
  {
    img: "https://m.media-amazon.com/images/I/61TM6Q9dvxL._AC_UX575_.jpg",
    title: "Roma Basic Sneaker",
    star: <AiFillStar className="ratings-start" />,
    reviews: "(123 reviews)",
    prevPrice: "₦5,000",
    newPrice: "30k",
    company: "Puma",
    color: "white",
    category: "sneakers",
  },
  {
    img: "https://m.media-amazon.com/images/I/7128-af7joL._AC_UY575_.jpg",
    title: "Pacer Future Doubleknit",
    star: <AiFillStar className="ratings-start" />,
    reviews: "(123 reviews)",
    prevPrice: "₦5,000",
    newPrice: "30k",
    company: "Puma",
    color: "black",
    category: "sneakers",
  },

  {
    img: "https://m.media-amazon.com/images/I/81xXDjojYKS._AC_UX575_.jpg",
    title: "Fusion Evo Golf Shoe",
    star: <AiFillStar className="ratings-start" />,
    reviews: "(123 reviews)",
    prevPrice: "₦5,000",
    newPrice: "20k",
    company: "Puma",
    color: "green",
    category: "sneakers",
  },
  {
    img: "https://m.media-amazon.com/images/I/719gdz8lsTS._AC_UX575_.jpg",
    title: "Rainbow Chex Skate",
    star: <AiFillStar className="ratings-start" />,
    reviews: "(123 reviews)",
    prevPrice: "₦5,000",
    newPrice: "20k",
    company: "Vans",
    color: "red",
    category: "flats",
  },
  {
    img: "https://m.media-amazon.com/images/I/71gpFHJlnoL._AC_UX575_.jpg",
    title: "Low-Top Trainers",
    star: <AiFillStar className="ratings-start" />,
    reviews: "(123 reviews)",
    prevPrice: "₦5,000",
    newPrice: "20k",
    company: "Vans",
    color: "white",
    category: "sandals",
  },
  {
    img: "https://m.media-amazon.com/images/I/71pf7VFs9CL._AC_UX575_.jpg",
    title: "Vans Unisex Low-Top",
    star: <AiFillStar className="ratings-start" />,
    reviews: "(123 reviews)",
    prevPrice: "₦5,000",
    newPrice: "20k",
    company: "Vans",
    color: "blue",
    category: "sandals",
  },
  {
    img: "https://m.media-amazon.com/images/I/61N4GyWcHPL._AC_UY575_.jpg",
    title: "Classic Bandana Sneakers",
    star: <AiFillStar className="ratings-start" />,
    reviews: "(123 reviews)",
    prevPrice: "₦5,000",
    newPrice: "10k",
    company: "Nike",
    color: "black",
    category: "sandals",
  },
  {
    img: "https://m.media-amazon.com/images/I/61bncQ44yML._AC_UX695_.jpg",
    title: "Chunky High Heel",
    star: <AiFillStar className="ratings-start" />,
    reviews: "(123 reviews)",
    prevPrice: "₦5,000",
    newPrice: "10k",
    company: "Vans",
    color: "black",
    category: "heels",
  },
  {
    img: "https://m.media-amazon.com/images/I/71czu7WgGuL._AC_UY695_.jpg",
    title: "Slip On Stiletto High Heel",
    star: <AiFillStar className="ratings-start" />,
    reviews: "(123 reviews)",
    prevPrice: "₦5,000",
    newPrice: "20k",
    company: "puma",
    color: "black",
    category: "heels",
  },
  {
    img: "https://m.media-amazon.com/images/I/61men05KRxL._AC_UY625_.jpg",
    title: "DREAM PAIRS Court Shoes",
    star: <AiFillStar className="ratings-start" />,
    reviews: "(123 reviews)",
    prevPrice: "₦5,000",
    newPrice: "30k",
    company: "Nike",
    color: "red",
    category: "heels",
  },
  {
    img: "https://m.media-amazon.com/images/I/519MRhRKGFL._AC_UX575_.jpg",
    title: "Nike Air Vapormax Plus",
    star: <AiFillStar className="ratings-start" />,
    reviews: "(123 reviews)",
    prevPrice: "₦5,000",
    newPrice: "10k",
    company: "Nike",
    color: "red",
    category: "sneakers",
  },

  {
    img: "https://m.media-amazon.com/images/I/51PGWTXgf-L._AC_UY625_.jpg",
    title: "Low Mid Block Heels",
    star: <AiFillStar className="ratings-start" />,
    reviews: "(123 reviews)",
    prevPrice: "₦5,000",
    newPrice: "10k",
    company: "Nike",
    color: "black",
    category: "heels",
  },
  {
    img: "https://m.media-amazon.com/images/I/616sA5XUKtL._AC_UY675_.jpg",
    title: "Chunky High Heel",
    star: <AiFillStar className="ratings-start" />,
    reviews: "(123 reviews)",
    prevPrice: "₦5,000",
    newPrice: "10k",
    company: "Adidas",
    color: "black",
    category: "heels",
  },
  {
    img: img6,
    title: "Chuky High Heel",
    star: <AiFillStar className="ratings-start" />,
    reviews: "(123 reviews)",
    prevPrice: "₦5,000",
    newPrice: "10k",
    company: "Adidas",
    color: "black",
    category: "heels",
  },
  {
    img: img7,
    title: "Chuky High Heel",
    star: <AiFillStar className="ratings-start" />,
    reviews: "(123 reviews)",
    prevPrice: "₦5,000",
    newPrice: "10k",
    company: "Adidas",
    color: "red",
    category: "heels",
  },
  {
    img: "https://m.media-amazon.com/images/I/71h5+MbEK7L._AC_UY625_.jpg",
    title: "Amore Fashion Stilettos",
    star: <AiFillStar className="ratings-start" />,
    reviews: "(123 reviews)",
    prevPrice: "₦5,000",
    newPrice: "30k",
    company: "Adidas",
    color: "white",
    category: "heels",
  },
  {
    img: "https://m.media-amazon.com/images/I/61uw5RDxKQL._AC_UY625_.jpg",
    title: "Bridal Sandals Glitter",
    star: <AiFillStar className="ratings-start" />,
    reviews: "(123 reviews)",
    prevPrice: "₦5,",
    newPrice: "10k",
    company: "Adidas",
    color: "black",
    category: "heels",
  },
  {
    img: "https://m.media-amazon.com/images/I/71yhoZP0l6L._AC_UY695_.jpg",
    title: "Wedding Prom Bridal",
    star: <AiFillStar className="ratings-start" />,
    reviews: "(123 reviews)",
    prevPrice: "₦5,000",
    newPrice: "10k",
    company: "Adidas",
    color: "black",
    category: "flats",
  },
  {
    img: img1,
    title: "Men Shoes",
    star: <AiFillStar className="ratings-start" />,
    reviews: "(123 reviews)",
    prevPrice: "₦5,000",
    newPrice: "10k",
    company: "Adidas",
    color: "black",
    category: "flats",
  },
];

export default data;